#
# @author Patrick Greyson
#
# Postmag - Postfix mail alias generator for Nextcloud
# Copyright (C) 2021
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "dev"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
      day: "thursday"
      
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
      day: "thursday"

