#
# @author Patrick Greyson
#
# Postmag - Postfix mail alias generator for Nextcloud
# Copyright (C) 2021
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Workflow for checking semantic labels
name: check-semantic-labels

on:
  pull_request:
    branches: [ dev ]
    types: [ opened, reopened, synchronize, labeled, unlabeled ]
    
jobs:
  check-parallel-runs:
    runs-on: ubuntu-latest
    outputs:
      parallelruns: ${{ steps.check.outputs.parallelruns }}
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Check for parallel runs
        id: check
        run: echo "::set-output name=parallelruns::$(python $GITHUB_WORKSPACE/.github/scripts/parallelRuns.py ${{ github.token }})"

      - name: Cleanup workspace
        run: rm -rf $GITHUB_WORKSPACE/*

  check-labels:
    runs-on: ubuntu-latest
    needs: [ check-parallel-runs ]
    if: ${{ needs.check-parallel-runs.outputs.parallelruns == 'False' }}
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Checkout app code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
    
      - name: Get pull request id
        run: echo "pr_id=$(echo $GITHUB_REF | cut -f3 -d/)" >> $GITHUB_ENV
        
      - name: Check labels
        run: python $GITHUB_WORKSPACE/.github/scripts/checkLabels.py $GITHUB_WORKSPACE/.github/config/semantic_labels.json $pr_id
